name: Update WakaTime Stats

on:
  schedule:
    - cron: "0 */6 * * *"  # every 6 hours
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: ImBIOS/waka-readme-stats@v1.0.3  # stable, minimalistic fork
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.PAT_1 }}

          #keep
          SHOW_DAYS_OF_WEEK: "True"      
          SHOW_EDITORS: "True"
          SHOW_OS: "True"
          SHOW_LANGUAGE: "True"          

          #hide
          SHOW_LINES_OF_CODE: "False"
          SHOW_COMMIT: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_UPDATED_DATE: "False"
          SHOW_TOTAL_CODE_TIME: "False"
          SHOW_PROJECTS: "False"
          SHOW_TIMEZONE: "False"
          SHOW_LOC_CHART: "False"
