name: WakaTime Readme Stats

on:
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}

          SHOW_TITLE: true
          TIME_RANGE: last_7_days
          LANG_COUNT: 5
          SHOW_TOTAL: false
          BLOCKS: ░▒▓█
